#! /bin/sh

brew install ag
brew install bat
brew install cookiecutter
brew install coreutils
brew install direnv
brew install entr
brew install fzf
brew install gdbm
brew install gnupg
brew install gnutls
brew install htop
brew install jq
brew install mas
brew install mycli
brew install node
brew install noti
brew install oniguruma
brew install openssl
brew install packer
brew install pgcli
brew install pkg-config
brew install prettyping
brew install pwgen
brew install pyenv
brew install pyenv-virtualenv
brew install python
brew install python3
brew install rclone
brew install readline
brew install sqlite
brew install telnet
brew install terraform
brew install tmux
brew install wget
brew install xz
brew install youtube-dl

brew tap jmespath/jmespath
brew install jp
