context.modules = [
    {   name = libpipewire-module-raop-discover
        args = {
            # Enable local discovery if desired (uncomment if needed)
            raop.discover-local = true
            #raop.latency.ms = 1000
            stream.rules = [
                {   matches = [
                        {    raop.ip = "~.*"
                             #raop.port = 1000
                             #raop.name = ""
                             #raop.hostname = ""
                             #raop.domain = ""
                             #raop.device = ""
                             #raop.transport = "tcp" | "udp" # Suggest explicit TCP for reliability
                             #raop.encryption.type = "none" | "RSA" | "auth_setup" | "fp_sap25"
                             #raop.audio.codec = "PCM" | "ALAC" | "AAC" | "AAC-ELD"
                             #raop.audio.codec = "PCM"       # Use lossless PCM for broad compatibility
                             #audio.channels = 2
                             #audio.format = "S16"
                             #audio.rate = 44100
                             #device.model = ""
                        }
                    ]
                    actions = {
                        create-stream = {
                            #raop.password = ""
                            stream.props = {
                                #target.object = ""
                                media.class = "Audio/Sink"
                            }
                        }
                    }
                }
            ]
        }
    },


    {   name = libpipewire-module-raop-sink
        args = {
            # Set the remote address and params to tunnel to
            raop.ip = "127.0.0.1"
            raop.port = 8190
            # raop.name = "wonkavator"
            # raop.hostname = "Wonkavator"
            raop.transport = "tcp"
            raop.encryption.type = "none"
            raop.audio.codec = "PCM"
            #raop.password = "****"
            audio.format = "S16"
            audio.rate = 44100
            audio.channels = 2
            audio.position = [ FL FR ]
        }
    }
]
