#! /usr/bin/env bash

# If on Linux, alias pbcopy and pbpaste to xclip equivalents
if command -v xclip &>/dev/null; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi